import { Tenant, Payment, Room, Complaint, Announcement } from '../contexts/DataContext';

export const sampleTenants: Omit<Tenant, 'id'>[] = [
  {
    name: 'Rahul Sharma',
    email: 'rahul.sharma@email.com',
    phone: '+91 9876543210',
    roomNumber: '101',
    joinDate: '2024-01-15',
    status: 'active',
    address: '123 Main Street, Mumbai, Maharashtra',
    emergencyContact: '+91 9876543211',
    deposit: 15000,
  },
  {
    name: 'Priya Patel',
    email: 'priya.patel@email.com',
    phone: '+91 9876543212',
    roomNumber: '102',
    joinDate: '2024-02-01',
    status: 'active',
    address: '456 Park Avenue, Delhi, Delhi',
    emergencyContact: '+91 9876543213',
    deposit: 12000,
  },
  {
    name: 'Amit Kumar',
    email: 'amit.kumar@email.com',
    phone: '+91 9876543214',
    roomNumber: '201',
    joinDate: '2024-01-20',
    status: 'active',
    address: '789 Garden Road, Bangalore, Karnataka',
    emergencyContact: '+91 9876543215',
    deposit: 18000,
  },
  {
    name: 'Sneha Gupta',
    email: 'sneha.gupta@email.com',
    phone: '+91 9876543216',
    roomNumber: '202',
    joinDate: '2024-03-01',
    status: 'inactive',
    address: '321 Lake View, Pune, Maharashtra',
    emergencyContact: '+91 9876543217',
    deposit: 10000,
  },
];

export const sampleRooms: Omit<Room, 'id'>[] = [
  {
    number: '101',
    type: 'single',
    rent: 8000,
    status: 'occupied',
    tenantId: '1',
    facilities: ['AC', 'WiFi', 'Attached Bathroom', 'Balcony'],
    floor: 1,
  },
  {
    number: '102',
    type: 'double',
    rent: 6000,
    status: 'occupied',
    tenantId: '2',
    facilities: ['Fan', 'WiFi', 'Shared Bathroom'],
    floor: 1,
  },
  {
    number: '103',
    type: 'single',
    rent: 7500,
    status: 'vacant',
    facilities: ['AC', 'WiFi', 'Attached Bathroom'],
    floor: 1,
  },
  {
    number: '201',
    type: 'triple',
    rent: 5000,
    status: 'occupied',
    tenantId: '3',
    facilities: ['Fan', 'WiFi', 'Shared Bathroom', 'Study Table'],
    floor: 2,
  },
  {
    number: '202',
    type: 'double',
    rent: 6500,
    status: 'maintenance',
    facilities: ['AC', 'WiFi', 'Attached Bathroom', 'Wardrobe'],
    floor: 2,
  },
  {
    number: '203',
    type: 'single',
    rent: 8500,
    status: 'vacant',
    facilities: ['AC', 'WiFi', 'Attached Bathroom', 'Balcony', 'Fridge'],
    floor: 2,
  },
];

export const samplePayments: Omit<Payment, 'id'>[] = [
  {
    tenantId: '1',
    tenantName: 'Rahul Sharma',
    amount: 8000,
    type: 'rent',
    status: 'paid',
    dueDate: '2024-09-01',
    paidDate: '2024-08-30',
    description: 'Monthly rent for September 2024',
  },
  {
    tenantId: '2',
    tenantName: 'Priya Patel',
    amount: 6000,
    type: 'rent',
    status: 'pending',
    dueDate: '2024-09-01',
    description: 'Monthly rent for September 2024',
  },
  {
    tenantId: '3',
    tenantName: 'Amit Kumar',
    amount: 5000,
    type: 'rent',
    status: 'overdue',
    dueDate: '2024-08-01',
    description: 'Monthly rent for August 2024',
  },
  {
    tenantId: '1',
    tenantName: 'Rahul Sharma',
    amount: 15000,
    type: 'deposit',
    status: 'paid',
    dueDate: '2024-01-15',
    paidDate: '2024-01-15',
    description: 'Security deposit',
  },
  {
    tenantId: '2',
    tenantName: 'Priya Patel',
    amount: 500,
    type: 'maintenance',
    status: 'paid',
    dueDate: '2024-09-15',
    paidDate: '2024-09-14',
    description: 'AC repair charges',
  },
  {
    tenantId: '3',
    tenantName: 'Amit Kumar',
    amount: 1000,
    type: 'other',
    status: 'pending',
    dueDate: '2024-09-20',
    description: 'Late payment penalty',
  },
];

export const sampleComplaints: Omit<Complaint, 'id'>[] = [
  {
    tenantId: '1',
    tenantName: 'Rahul Sharma',
    title: 'AC not working properly',
    description: 'The air conditioner in room 101 is not cooling properly. It makes strange noises and barely cools the room.',
    category: 'maintenance',
    status: 'open',
    priority: 'high',
    createdDate: '2024-09-25',
  },
  {
    tenantId: '2',
    tenantName: 'Priya Patel',
    title: 'Noise from neighboring room',
    description: 'There is excessive noise coming from the room next door during night hours, disturbing sleep.',
    category: 'noise',
    status: 'in-progress',
    priority: 'medium',
    createdDate: '2024-09-20',
  },
  {
    tenantId: '3',
    tenantName: 'Amit Kumar',
    title: 'Water leakage in bathroom',
    description: 'There is water leakage from the ceiling in the bathroom. The floor gets wet frequently.',
    category: 'maintenance',
    status: 'resolved',
    priority: 'high',
    createdDate: '2024-09-15',
    resolvedDate: '2024-09-22',
  },
  {
    tenantId: '2',
    tenantName: 'Priya Patel',
    title: 'WiFi connectivity issues',
    description: 'Internet connection is very slow and frequently disconnects. Unable to work from home properly.',
    category: 'maintenance',
    status: 'open',
    priority: 'medium',
    createdDate: '2024-09-28',
  },
];

export const sampleAnnouncements: Omit<Announcement, 'id'>[] = [
  {
    title: 'Monthly Maintenance Schedule',
    content: 'Regular maintenance work will be conducted on the first Saturday of every month from 9 AM to 5 PM. This includes cleaning of common areas, checking electrical systems, and plumbing inspection.',
    type: 'maintenance',
    priority: 'medium',
    createdDate: '2024-09-01',
    expiryDate: '2024-12-31',
    isActive: true,
  },
  {
    title: 'New House Rules',
    content: 'Please note the updated house rules: 1) No loud music after 10 PM, 2) Visitors must register at reception, 3) Keep common areas clean, 4) No smoking in rooms or corridors.',
    type: 'rule',
    priority: 'high',
    createdDate: '2024-09-15',
    isActive: true,
  },
  {
    title: 'Diwali Celebration',
    content: 'Join us for Diwali celebration on October 31st at 7 PM in the common hall. There will be decorations, traditional food, and cultural programs. All residents are invited!',
    type: 'event',
    priority: 'low',
    createdDate: '2024-09-20',
    expiryDate: '2024-11-01',
    isActive: true,
  },
  {
    title: 'Power Outage Notice',
    content: 'There will be a scheduled power outage on September 30th from 2 PM to 4 PM for electrical maintenance. Please plan accordingly.',
    type: 'maintenance',
    priority: 'high',
    createdDate: '2024-09-28',
    expiryDate: '2024-09-30',
    isActive: true,
  },
  {
    title: 'Rent Payment Reminder',
    content: 'This is a reminder that monthly rent is due on the 1st of every month. Late payments will incur a penalty of ₹100 per day. Please ensure timely payment.',
    type: 'general',
    priority: 'medium',
    createdDate: '2024-08-25',
    isActive: false,
  },
];

export const initializeSampleData = () => {
  return {
    tenants: sampleTenants.map((tenant, index) => ({ ...tenant, id: (index + 1).toString() })),
    rooms: sampleRooms.map((room, index) => ({ ...room, id: (index + 1).toString() })),
    payments: samplePayments.map((payment, index) => ({ ...payment, id: (index + 1).toString() })),
    complaints: sampleComplaints.map((complaint, index) => ({ ...complaint, id: (index + 1).toString() })),
    announcements: sampleAnnouncements.map((announcement, index) => ({ ...announcement, id: (index + 1).toString() })),
  };
};
